blank_issues_enabled: false

contact_links:
  - name: 🗣️ Discussions
    url: https://github.com/orgs/selfshop-dev/discussions
    about: |
      Вопросы по использованию, архитектуре и идеи для обсуждения.
      Не используйте issues для общих вопросов.